# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
