# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_productdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='sku',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
